version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: whatsapp-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: whatsapp-clone
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - whatsapp-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: whatsapp-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/whatsapp-clone
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_jwt_key_change_this}
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - whatsapp-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: whatsapp-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
    depends_on:
      - server
    networks:
      - whatsapp-network

volumes:
  mongodb_data:

networks:
  whatsapp-network:
    driver: bridge

